ignore:
  - setup.py     # ignore the `setup.py` file
  - .venv/       # ignore everything in the `.venv` directory
  - .tox/       # ignore everything in the `.venv` directory
  - tests/       # ignore everything in the `tests` directory
  - test_*.py    # ignore all Python test files
  - '*_test.py'  # strings beginning with * must be quoted

rule_settings:
  enable: [default]
  disable: []
  rule_types:
    - refactoring
    - suggestion
    - comment
  python_version: '3.9'

rules: []

metrics:
  quality_threshold: 25.0

github:
  labels: []
  ignore_labels:
    - sourcery-ignore
  request_review: author
  sourcery_branch: sourcery/{base_branch}

clone_detection:
  min_lines: 3
  min_duplicates: 2
  identical_clones_only: false

proxy:
  no_ssl_verify: false