PHONETIC_LIST = [
    "Alpha",
    "Bravo",
    "Charlie",
    "Delta",
    "Echo",
    "Foxtrot",
    "Golf",
    "Hotel",
    "India",
    "Juliet",
    "Kilo",
    "Lima",
    "Mike",
    "November",
    "Oscar",
    "Papa",
    "Quebec",
    "Romeo",
    "Sierra",
    "Tango",
    "Uniform",
    "Victor",
    "Whiskey",
    "Xray",
    "Yankee",
    "Zulu",
]

PHONETIC_DICT = {
    "A": "Alpha",
    "B": "Bravo",
    "C": "Charlie",
    "D": "Delta",
    "E": "Echo",
    "F": "Foxtrot",
    "G": "Golf",
    "H": "Hotel",
    "I": "India",
    "J": "Juliet",
    "K": "Kilo",
    "L": "Lima",
    "M": "Mike",
    "N": "November",
    "O": "Oscar",
    "P": "Papa",
    "Q": "Quebec",
    "R": "Romeo",
    "S": "Sierra",
    "T": "Tango",
    "U": "Uniform",
    "V": "Victor",
    "W": "Whiskey",
    "X": "Xray",
    "Y": "Yankee",
    "Z": "Zulu",
}

LEO_PHONETIC_LIST = [
    "Adam",
    "Boy",
    "Charles",
    "David",
    "Edward",
    "Frank",
    "George",
    "Henry",
    "Ida",
    "John",
    "King",
    "Lincoln",
    "Mary",
    "Nora",
    "Ocean",
    "Paul",
    "Queen",
    "Robert",
    "Sam",
    "Tom",
    "Union",
    "Victor",
    "William",
    "Xray",
    "Young",
    "Zebra",
]

LEO_PHONETIC_DICT = {
    "A": "Adam",
    "B": "Boy",
    "C": "Charles",
    "D": "David",
    "E": "Edward",
    "F": "Frank",
    "G": "George",
    "H": "Henry",
    "I": "Ida",
    "J": "John",
    "K": "King",
    "L": "Lincoln",
    "M": "Mary",
    "N": "Nora",
    "O": "Ocean",
    "P": "Paul",
    "Q": "Queen",
    "R": "Robert",
    "S": "Sam",
    "T": "Tom",
    "U": "Union",
    "V": "Victor",
    "W": "William",
    "X": "Xray",
    "Y": "Young",
    "Z": "Zebra",
}

def phonetic_spelling(callsign):
    translation = []
    for char in callsign:
        if char in PHONETIC_DICT:
            translation.append(PHONETIC_DICT[char])
        else:
            translation.append(char)
    return " ".join(translation)


__all__ = ("PHONETIC_LIST", "PHONETIC_DICT", "LEO_PHONETIC_LIST", "LEO_PHONETIC_DICT", "phonetic_spelling")
