= Contributing

Welcome to the "`gwpycore`" contributor's guide.
This document is mainly about getting developers up to speed, but https://opensource.guide/how-to-contribute[other kinds of contributions] are also very much appreciated.
Please notice, all users and contributors are expected to be *open, considerate, reasonable, and respectful*.
When in doubt, https://www.python.org/psf/conduct/[Python Software Foundation's Code of Conduct] is a good reference for specific behavior guidelines.



== The GitHub Repository

The source code, documentation, and issues (bug reports, feature requests) are all in the GitHub repository: https://github.com/gruntwurk/gwpycore[]

If you are new to using https://git-scm.com[git] or have never collaborated in a project previously, please have a look at https://www.contribution-guide.org/[contribution-guide.org] by FreeCodeCamp.

See the link:/doc/INSTALL.doc[install] notes for how to properly work with a cloned copy of this repository.
(That way, any changes that you make to your copy of the source will be instantly available to your projects that use `gwpycore`.)



== Reporting Bugs/Issues or Requesting New Features

First of all, if you experience a bug or other issue with gwpycore, or if there is a feature you would like to see added, please look to see if the https://github.com/gruntwurks/gwpycore/issues[issue tracker] already has a report on it.
If you find something related, please contribute to the conversation there; otherwise, feel free to fire off a new report.

TIP: Please don't forget to include the closed issues in your search.
Sometimes a solution was already reported, and the problem is considered *solved*.
You can comment of a closed issue, requesting that it be reopened.

New issue reports should include information about your programming environment (e.g. operating system, Python version) and steps to reproduce the problem.
Please try also to simplify the reproduction steps to a very minimal example that still illustrates the problem you are facing.
By removing other factors, you help us to identify the root cause of the issue.



== Documentation Improvements

You can help improve the gwpycore docs by making them more readable and coherent, or by adding missing information and correcting mistakes.

The gwpycore documentation uses https://www.sphinx-doc.org/en/master/[Sphinx] as its main documentation compiler.
This means that the docs are kept in the same repository as the project code, and that any documentation update is done in the same way as a code contribution.

TIP: Please notice that the https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files[GitHub web interface] provides a quick way of proposing changes in gwpycore's files.
While this mechanism canbe tricky for normal code contributions, it works perfectly fine for contributing to the docs, and can be quite handy.

If you are interested in trying this method out, please navigate to the `docs` folder in the source https://github.com/gruntwurks/gwpycore[repository], and then to the file in question.
Click the little pencil icon at the top, to open https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files[GitHub's code editor].
Once you finish editing the file, please write a message in the form at the bottom of the page describing your motivations behind the changes and submit your proposal.

When working on documentation changes in your local machine, you can compile them using tox (`tox -e docs`) and use Python's built-in web server for a preview in your web browser (`http://localhost:8000`):

----
python3 -m http.server --directory 'docs/_build/html'
----


== Code Contributions

See: link:/doc_technical/DESIGN_NOTES.adoc[Design Notes]


=== Submit an Issue

Before you work on any non-trivial code contribution it's best to first create a report in the https://github.com/gruntwurks/gwpycore/issues[issue tracker] to start a discussion on the subject.
This often provides additional considerations and avoids unnecessary work.


=== Create an Environment

Before you start coding, we recommend creating an isolated link:/doc_technical/VIRTUAL_ENVIRONMENTS.adoc[virtual environment] to avoid any problems with your installed Python packages.


=== Clone the Repository

. Create a user account on GitHub if you do not already have one.
. Fork the project https://github.com/gruntwurks/gwpycore[repository]: click on the *Fork* button near the top of the page. 
This creates a copy of the code under your account on GitHub.
. Clone this copy to your local disk:

----
git clone git@github.com:YourLogin/gwpycore.git
cd gwpycore
----

. You should run `pip install -U pip setuptools -e .` to be able to import the package under development in the Python REPL.

. Install `pre-commit`. 
gwpycore comes with a lot of hooks configured to automatically help the developer to check the code being written.

----
pip install pre-commit
pre-commit install
----


=== Implement your changes

. Create a branch to hold your changes (`git checkout -b my-feature`). 
Never work on the main branch!

. Start your work on this branch. 
Don't forget to add https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html[docstrings] to new functions, modules and classes, especially if they are part of public APIs.

. Add yourself to the list of contributors in `AUTHORS.adoc`.

. When you’re done editing, record your changes in https://git-scm.com[git]:

----
git add <MODIFIED FILES>
git commit
----


Please make sure to see the validation messages from `pre-commit` and fix any eventual issues.
This should automatically use https://flake8.pycqa.org/en/stable/[flake8] and /https://pypi.org/project/black/[black] to check/fix the code style in a way that is compatible with the project.

IMPORTANT: Don't forget to add unit tests and documentation in the case that your contribution adds an additional feature and is not just a bugfix.

Moreover, writing a https://chris.beams.io/posts/git-commit[descriptive commit message] is highly encouraged.
In case of doubt, you can check the commit history to look for recurring communication patterns:

----
git log --graph --decorate --pretty=oneline --abbrev-commit --all
----


. Please check that your changes don't break any unit tests with `tox` (after having installed tox with `pip install tox`).
You can also use tox to run several other pre-configured tasks in the repository.
Use `tox -av` to see a list of the available checks.


=== Submit Your Contribution

. If everything works fine, push your local branch to GitHub with:

----
git push -u origin my-feature
----

. Go to the web page of your fork and click "`Create pull request`" to send your changes for review.
Find more detailed information in https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request[creating a PR].
You might also want to open the PR as a draft first and mark it as ready for review after the feedback from the continuous integration (CI) system or any required fixes.


=== Troubleshooting

The following tips can be used when facing problems to build or test the package:

. Make sure to fetch all the tags from the upstream https://github.com/gruntwurks/gwpycore[repository].
The command `git describe --abbrev=0 --tags` should return the version you are expecting. 
If you are trying to run CI scripts in a fork repository, make sure to push all the tags.
You can also try to remove all the egg files or the complete egg folder, i.e. `.eggs`, as well as the `*.egg-info` folders in the `src` folder or potentially in the root of your project.

. Sometimes `tox` misses out when new dependencies are added, especially to `setup.cfg` and `docs/requirements.txt`.
If you find any problems with missing dependencies when running a command with `tox`, try to recreate the `tox` environment using the `-r` flag.
For example, instead of `tox -e docs` try running `tox -r -e docs`.

. Make sure to have a reliable `tox` installation that uses the correct Python version (e.g., 3.7+). 
When in doubt you can run `tox --version`.

If you have trouble and are seeing weird errors upon running tox, you can also try to create a dedicated https://realpython.com/python-virtual-environments-a-primer/[virtual environment] with a `tox` binary freshly installed. 
For example:

----
virtualenv .venv
source .venv/bin/activate
.venv/bin/pip install tox
.venv/bin/tox -e all
----

. https://docs.pytest.org/en/stable/how-to/failures.html#using-python-library-pdb-with-pytest[Pytest can drop you] in an interactive session in the case an error occurs.
In order to do that you need to pass a `--pdb` option (for example by running `tox -- -k <NAME OF THE FALLING TEST> --pdb`).
   You can also setup breakpoints manually instead of using the `--pdb` option.



== Maintainer tasks


=== Releases

If you are part of the group of maintainers and have correct user permissions on https://pypi.org/[PyPI], the following steps can be used to release a new version for gwpycore:

. Make sure all unit tests are successful.

. Tag the current commit on the main branch with a release tag, e.g., `v1.2.3`.

. Push the new tag to the upstream https://github.com/gruntwurks/gwpycore[repository], e.g. `git push upstream v1.2.3`

. Clean out the `dist` and `build` folders with `tox -e clean` (or `rm -rf dist build`) to avoid confusion with old builds and Sphinx docs.

. Run `tox -e build` and check that the files in `dist` have the correct version (no `.dirty` or https://git-scm.com[git] hash) according to the https://git-scm.com[git] tag.
Also check the sizes of the distributions, if they are too big (e.g., >500KB), unwanted clutter may have been accidentally included.

. Run `tox -e publish -- --repository pypi` and check that everything was uploaded to https://pypi.org/[PyPI] correctly.



Next Topic: link:/doc_technical/DEVELOPMENT_SETUP.adoc[Development Environment Setup]
