= Contributing

Welcome to the *gwpycore* contributor's guide.

This document focuses on getting any potential contributor familiarized with the development processes, but other kinds of contributions besides coding are also appreciated (see https://opensource.guide/how-to-contribute[]).

Please notice, all users and contributors are expected to be *open, considerate, reasonable, and respectful*.
When in doubt, "`Python Software Foundation's Code of Conduct`" is a good reference in terms of behavior guidelines.



== The GitHub Repository

The source code, documentation, and issues (bug reports, feature requests) are all in the GitHub repository: https://github.com/gruntwurk/gwpycore[]

If you are new to using git or have never collaborated in a project previously, please have a look at https://www.contribution-guide.org[].

See the link:/doc/INSTALL.doc[install] notes for how to work with a cloned copy of this repository.
(Any changes that you make to your copy of the source will be instantly available to your projects that use `gwpycore`.)



== Issue Reports

If you experience bugs or general issues with `gwpycore`, please have a look on https://github.com/gruntwurk/gwpycore/issues[].
If you don't see anything useful there, please feel free to fire an issue report.

TIP: Please don't forget to include the closed issues in your search.
Sometimes a solution was already reported, and the problem is considered *solved*.

New issue reports should include information about your programming environment (e.g. operating system, Python version) and steps to reproduce the problem.
Please try also to simplify the reproduction steps to a very minimal example that still illustrates the problem you are facing.
By removing other factors, you help us to identify the root cause of the issue.



== Documentation Improvements

You can help improve `gwpycore` docs by making them more readable and coherent, or by adding missing information and correcting mistakes.

`gwpycore` documentation uses AsciiDoc as its main documentation compiler.
This means that the docs are kept in the same repository as the project code, and
that any documentation update is done in the same way as a code contribution.

TIP: Please notice that the GitHub web interface provides a quick way of propose changes in `gwpycore`'s files. While this mechanism canbe tricky for normal code contributions, it works perfectly fine for contributing to the docs, and can be quite handy.

If you are interested in trying this method out, please navigate to the `docs` folder in the repository, find which file you would like to propose changes and click in the little pencil icon at the top, to open GitHub's code editor.
Once you finish editing the file, please write a message in the form at the bottom of the page describing which changes have you made and what are the motivations behind them and submit your proposal.

When working on documentation changes in your local machine, you can compile them using tox (`tox -e docs`) and use Python's built-in web server for a preview in your web browser (`http://localhost:8000`):

    python3 -m http.server --directory 'docs/build/html'



== Code Contributions

See: link:/doc_technical/DESIGN_NOTES.adoc[Design Notes]


=== Submit an issue

Before you work on any non-trivial code contribution it's best to first create a report in the issue tracker (see above) to start a discussion on the subject.
This often provides additional considerations and avoids unnecessary work.


=== Create an environment

Before you start coding, we recommend creating an isolated link:/doc_technical/VIRTUAL_ENVIRONMENTS.adoc[virtual environment] to avoid any problems with your installed Python packages.


=== Clone the repository

. Create a user account on GitHub if you do not already have one.
. Fork the project repository: click on the *Fork* button near the top of the page. This creates a copy of the code under your account on GitHub.
. Clone this copy to your local disk:

    git clone git@github.com:YourLogin/gwpycore.git
    cd gwpycore

. You should run `pip install -U pip setuptools -e .` to be able to import the package under development in the Python REPL.

. Install `pre-commit` (`gwpycore` comes with a lot of hooks configured to automatically help the developer to check the code being written.):

    pip install pre-commit
    pre-commit install


=== Implement your changes

. Create a branch to hold your changes (`git checkout -b my-feature`) and start making changes. Never work on the main branch!

. Start your work on this branch. Don't forget to add docstrings to new functions, modules and classes, especially if they are part of public APIs.

. Add yourself to the list of contributors in `AUTHORS.adoc`.

. When you’re done editing, record your changes in git:

    git add <MODIFIED FILES>
    git commit


   Please make sure to see the validation messages from `pre-commit` and fix
   any eventual issues.
   This should automatically use flake8/black to check/fix the code style in a way that is compatible with the project.

IMPORTANT: Don't forget to add unit tests and documentation in the case that your contribution adds an additional feature and is not just a bugfix.

Moreover, writing a descriptive commit message is highly recommended.
In case of doubt, you can check the commit history with:

    git log --graph --decorate --pretty=oneline --abbrev-commit --all

to look for recurring communication patterns.

. Please check that your changes don't break any unit tests with `tox` (after having installed tox with `pip install tox`).
You can also use tox to run several other pre-configured tasks in the repository.
Try `tox -av` to see a list of the available checks.


=== Submit your contribution

. If everything works fine, push your local branch to GitHub with:

    git push -u origin my-feature

. Go to the web page of your fork and click |contribute button| to send your changes for review.

Find more detailed information in `creating a Pull Request`.
You might also want to open the PR as a draft first and mark it as ready for review after the feedback from the continuous integration (CI) system or any required fixes.


=== Troubleshooting

The following tips can be used when facing problems to build or test the package:

. Make sure to fetch all the tags from the upstream repository_.
   The command `git describe --abbrev=0 --tags` should return the version you
   are expecting. If you are trying to run CI scripts in a fork repository,
   make sure to push all the tags.
   You can also try to remove all the egg files or the complete egg folder, i.e.,
   `.eggs`, as well as the `*.egg-info` folders in the `src` folder or
   potentially in the root of your project.

. Sometimes |tox|_ misses out when new dependencies are added, especially to
   `setup.cfg` and `docs/requirements.txt`. If you find any problems with
   missing dependencies when running a command with |tox|_, try to recreate the
   `tox` environment using the `-r` flag. For example, instead of::

    tox -e docs

   Try running::

    tox -r -e docs

. Make sure to have a reliable |tox|_ installation that uses the correct
   Python version (e.g., 3.7+). When in doubt you can run::

    tox --version
    # OR
    which tox

   If you have trouble and are seeing weird errors upon running |tox|_, you can
   also try to create a dedicated `virtual environment`_ with a |tox|_ binary
   freshly installed. For example::

    virtualenv .venv
    source .venv/bin/activate
    .venv/bin/pip install tox
    .venv/bin/tox -e all

. `Pytest can drop you`_ in an interactive session in the case an error occurs.
   In order to do that you need to pass a `--pdb` option (for example by
   running `tox -- -k <NAME OF THE FALLING TEST> --pdb`).
   You can also setup breakpoints manually instead of using the `--pdb` option.



== Maintainer tasks


=== Releases

If you are part of the group of maintainers and have correct user permissions on PyPI, the following steps can be used to release a new version for `gwpycore`:

. Make sure all unit tests are successful.
. Tag the current commit on the main branch with a release tag, e.g., `v1.2.3`.
. Push the new tag to the upstream repository_, e.g., `git push upstream v1.2.3`
. Clean up the `dist` and `build` folders with `tox -e clean` to avoid confusion with old builds and docs.
. Run `tox -e build` and check that the files in `dist` have the correct version (no `.dirty` or git_ hash) according to the git tag.
Also check the sizes of the distributions, if they are too big (e.g., >500KB), unwanted clutter may have been accidentally included.
. Run `tox -e publish -- --repository pypi` and check that everything was uploaded to PyPI_ correctly.




Next Topic: link:/doc_technical/DEVELOPMENT_SETUP.adoc[Development Environment Setup]
